#pragma once

#include <QtCore/qglobal.h>

#if defined(PELUXDEVICEMANAGER_LIBRARY)
#  define PELUXDEVICEMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PELUXDEVICEMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif
